//@ui5-bundle simasgrilo/github/io/Component-preload.js
sap.ui.require.preload({
	"simasgrilo/github/io/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","simasgrilo/github/io/model/models","sap/ui/core/IconPool"],function(e,i,t,o){"use strict";return e.extend("simasgrilo.github.io.Component",{metadata:{manifest:"json"},init:function(){o.registerFont({fontFamily:"SAP-icons-TNT",collectionName:"SAP-icons-TNT",fontURI:sap.ui.require.toUrl("sap/tnt/themes/base/fonts")});e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"simasgrilo/github/io/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sap/base/Log"],function(n,o,e){"use strict";return n.extend("com.simasgrilo.homepage.homepageui5.controller.App",{onInit:function(){const n=new o;fetch("./model/summary.json")},onEmailPress:function(){window.open("mailto:simasgrilo86@gmail.com")},onGithubPress:function(){window.open("https://github.com/simasgrilo")},onLinkedinPress:function(){window.open("https://www.linkedin.com/in/simasgrilo/")},onSummaryPress:function(){var n=this.getOwnerComponent().getRouter();n.navTo("summary")},onSkillsPress:function(){var n=this.getOwnerComponent().getRouter();n.navTo("skills")},onExperiencePress:function(){var n=this.getOwnerComponent().getRouter();n.navTo("experience")},onEducationPress:function(){var n=this.getOwnerComponent().getRouter();n.navTo("education")},onProjectsPress:function(){var n=this.getOwnerComponent().getRouter();n.navTo("projects")}})});
},
	"simasgrilo/github/io/controller/Experience.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/Text","sap/m/HBox","sap/m/VBox","sap/m/Title","sap/m/Panel"],function(e,t,n,a,i,r){"use strict";return e.extend("simasgrilo.github.io.controller.Experience",{onInit:function(){var e=this.getView().byId("experiencePage");var n=this.getOwnerComponent().getModel("experienceModel");var a=n.getData()["Experience"];for(let n of a){var i=new r({headerText:n["JobDescription"]+" @ "+n["Company"]+"\t\t\t\t"+n["TimeFrame"],expandable:true});n["Activities"].forEach(e=>{let n=e+"\n";let a=new t({text:n,renderWhitespace:true});a.addStyleClass("bullet-list");i.addContent(a)});e.addContent(i)}}})});
},
	"simasgrilo/github/io/controller/Main.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(i){"use strict";return i.extend("simasgrilo.github.io.controller.Main",{onInit:function(){}})});
},
	"simasgrilo/github/io/controller/Projects.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/Panel","sap/m/Text","sap/m/Label","sap/m/VBox","sap/m/Link"],function(e,t,n,a,d,l){"use strict";return e.extend("simasgrilo.github.io.controller.Projects",{onInit:function(){const e=this.getOwnerComponent().getModel("projectsModel");const s=e["oData"]["Experience"];const o=this.getView().byId("projects");const i=this.getOwnerComponent().getModel("i18n").getResourceBundle();for(let e of s){let s=new t({headerText:e["Title"],expandable:true});let r=new d({});let p=new a({text:i.getText("publishedAt")});p.addStyleClass("sapUiSmallMarginEnd");let m=new n({text:e["PublishedAt"]});m.addStyleClass("sapUiSmallMarginEnd");r.addItem(p).addItem(m);p=new a({text:i.getText("year")});p.addStyleClass("sapUiSmallMarginEnd");m=new n({text:e["Year"]});m.addStyleClass("sapUiSmallMarginEnd");r.addItem(p).addItem(m);p=new a({text:i.getText("projectsDescription")});r.addItem(p);s.addContent(r);e["Description"].forEach(e=>{let t=new n({text:e+"\n",renderWhitespace:true});t.addStyleClass("bullet-list");s.addContent(t)});let c=new d({});let x=new a({text:i.getText("repoLabel")});x.addStyleClass("sapUiSmallMarginEnd");let g=new l({text:e["Repository"],href:e["Repository"]});c.addItem(x).addItem(g);s.addContent(c);o.addContent(s)}}})});
},
	"simasgrilo/github/io/controller/Skills.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/Text"],function(e,t){"use strict";return e.extend("com.simasgrilo.homepage.homepageui5.controller.Skills",{onInit:function(){const e=this.getOwnerComponent().getModel("skillsModel");const n=e["oData"]["skills"];const o=this.getView().byId("skillsPage");var s="";n.forEach(e=>{s+=e+"\n\n"});var i=new t({text:s+"\n",renderWhitespace:true,wrapping:true});o.addContent(i)}})});
},
	"simasgrilo/github/io/controller/Summary.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/Text","sap/m/FlexBox"],function(e,t,n){"use strict";return e.extend("com.simasgrilo.homepage.homepageui5.controller.Summary",{onInit:function(){const e=this.getOwnerComponent().getModel("summaryModel");const o=e["oData"]["summary"];const r=this.getView().byId("summary");var s="";const a=new n("summaryFb",{alignItems:"Start",height:"500px",justifyContent:"Center"});for(let e of o){s+=e+"\n\n"}var i=new t({text:s+"\n",renderWhitespace:true,wrapping:true});a.addItem(i);r.addContent(a)},onClickMe:function(){console.log(this.getView().getModel("summaryModel"))}})});
},
	"simasgrilo/github/io/controls/ExpTile.js":function(){
sap.ui.define(["sap/ui/core/Control","sap/m/VBox","sap/m/HBox","sap/m/Title","sap/m/Text"],function(e,t,i,s,a){"use strict";return e.extend("simasgrilo.github.io.controls.ExpTile",{metadata:{properties:{jobTitle:{type:"string",defaultValue:""},tenure:{type:"string",defaultValue:""},jobDesctiption:{type:"sap.m.Text"}},aggregations:{_items:{type:"sap.m.VBox",multiple:false,visibility:"hidden"}}},init:function(){},renderer:function(e,t){}})});
},
	"simasgrilo/github/io/i18n/i18n.properties":'# This is the resource bundle for com.simasgrilo.homepage.homepageui5\r\n\r\n#Texts for manifest.json\r\n\r\n#XTIT: Application name\r\nappTitle=simasgrilo\r\n\r\n#YDES: Application description\r\nappDescription=A simple homepage carrying CV information built using SAPUI5\r\n#XTIT: Main view title\r\ntitle=simasgrilo\r\n\r\nsummaryTitle=A little About Me\r\nskillsTitle=Main Technical Skills\r\nexperienceTitle=Main Experience\r\n#projects-related i18n info\r\nprojectsTitle=Projects\r\nprojectsSubTitle=Some of the projects i have worked on besides my job in the past few years. \r\n#venue where the work was published\r\npublishedAt=Published at\r\n#year of publication\r\nyear=Year\r\nprojectsDescription=Description\r\nlinkLabel=You can find more details in my\r\nrepoLabel=Repository',
	"simasgrilo/github/io/manifest.json":'{"_version":"1.59.0","sap.app":{"id":"simasgrilo.github.io","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.13.5","toolsId":"254cd67b-d119-43d2-aeb5-1456f27bdabc"},"dataSources":{"summaryModel":{"type":"JSON","uri":"model/summary.json"},"skillsModel":{"type":"JSON","uri":"model/skills.json"},"experienceModel":{"type":"JSON","uri":"model/experience.json"},"projectsModel":{"type":"JSON","uri":"model/projects.json"}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.124.0","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"simasgrilo.github.io.i18n.i18n"}},"summaryModel":{"dataSource":"summaryModel"},"skillsModel":{"dataSource":"skillsModel"},"experienceModel":{"dataSource":"experienceModel"},"projectsModel":{"dataSource":"projectsModel"}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"simasgrilo.github.io.view","controlId":"app","clearControlAggregation":false},"routes":[{"name":"summary","pattern":"","target":["master","summary"]},{"name":"skills","pattern":"skills","target":["master","skills"]},{"name":"experience","pattern":"experience","target":["master","experience"]},{"name":"education","pattern":"education","target":["master","education"]},{"name":"projects","pattern":"projects","target":["master","projects"]}],"targets":{"master":{"viewType":"XML","transition":"slide","controlAggregation":"masterPages","viewName":"App","viewLevel":0},"summary":{"viewType":"XML","transition":"slide","controlAggregation":"detailPages","viewName":"Summary","viewLevel":1},"skills":{"viewType":"XML","transition":"slide","controlAggregation":"detailPages","viewName":"Skills","viewLevel":1},"experience":{"viewType":"XML","transition":"slide","controlAggregation":"detailPages","viewName":"Experience","viewLevel":1},"education":{"viewType":"XML","transition":"slide","controlAggregation":"detailPages","viewName":"Education","viewLevel":1},"projects":{"viewType":"XML","transition":"slide","controlAggregation":"detailPages","viewName":"Projects","viewLevel":1}}},"rootView":{"viewName":"simasgrilo.github.io.view.App","type":"XML","async":true,"id":"App"}}}',
	"simasgrilo/github/io/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"simasgrilo/github/io/view/App.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.App"\r\n    xmlns:html="http://www.w3.org/1999/xhtml"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"><SplitApp id="app"><masterPages><Page ><Image src="../static/photo.jpeg" height="300px" width="350px"></Image><HBox ><Panel ><Text text="Erick Simas Grilo" textAlign="End"></Text><Text text="Application Development Team Lead @ Accenture"></Text><Button icon="sap-icon://email" text="Email" press="onEmailPress"></Button><Button icon="sap-icon://SAP-icons-TNT/github" text="GitHub" press="onGithubPress"></Button><Button icon="sap-icon://SAP-icons-TNT/user" text="LinkedIn" press="onLinkedinPress"></Button></Panel></HBox><content><List id="topicsList"><ActionListItem id="summaryItem" text="Summary" press="onSummaryPress"></ActionListItem><ActionListItem id="skillsItem" text="Skills" press="onSkillsPress"></ActionListItem><ActionListItem id="experienceItem" text="Experience" press="onExperiencePress"></ActionListItem><ActionListItem id="educationItem" text="Education" press="onEducationPress"></ActionListItem><ActionListItem id="projectsItem" text="Projects" press="onProjectsPress"></ActionListItem></List></content></Page></masterPages><detailPages></detailPages></SplitApp></mvc:View>\r\n',
	"simasgrilo/github/io/view/Education.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.Main"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"></mvc:View>\r\n',
	"simasgrilo/github/io/view/Experience.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.Experience"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"><Page id="experiencePage"><content><VBox alignItems="Center"\r\n                  height="100px"><Title text="{i18n>experienceTitle}"\r\n                       titleStyle="H2"></Title></VBox></content></Page></mvc:View>\r\n\r\n\r\n            \r\n            ',
	"simasgrilo/github/io/view/Main.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.Main"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"></mvc:View>\r\n',
	"simasgrilo/github/io/view/Projects.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.Projects"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"><Page id="projects"><content><VBox alignItems="Center"><Title text="{i18n>projectsTitle}" \r\n                       titleStyle="H2"></Title><Text text="{i18n>projectsSubTitle}"></Text><HBox ><Label text="{i18n>linkLabel}" class="sapUiTinyMarginBottom sapUiTinyMarginEnd"></Label><Link text="Lattes" href="https://buscatextual.cnpq.br/buscatextual/cv?id=1599662706989254"></Link></HBox></VBox></content></Page></mvc:View>\r\n',
	"simasgrilo/github/io/view/Skills.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.Skills"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"><Page id="skillsPage"><VBox height="100px"\r\n              alignItems="Center"><Title text="{i18n>skillsTitle}" titleStyle="H2"></Title></VBox></Page></mvc:View>\r\n',
	"simasgrilo/github/io/view/Summary.view.xml":'<mvc:View controllerName="simasgrilo.github.io.controller.Summary"\r\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\r\n    xmlns="sap.m"><Page id="summary"><VBox \r\n            height="100px" \r\n            alignItems="Center"><Title text="A Little About Me" titleStyle="H2"></Title></VBox></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
