# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  checks: write
  deployments: write
  
jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci #clean install for all dependencies in package.json
    - run: npm run build --if-present
    - run: npm test --if-present
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

  # Single deploy job since we're just deploying
  #deploy:
  #  environment:
  #    name: github-pages
  #    url: ${{ steps.deployment.outputs.page_url }}
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #    - name: Setup Pages
  #      uses: actions/configure-pages@v5
  #    - name: Upload artifact
  #      uses: actions/upload-pages-artifact@v3
  #      with:
  #        # Upload folder with the result of the build
  #        path: '../dist'
  #    - name: Deploy to GitHub Pages
  #      id: deployment
  #      uses: actions/deploy-pages@v4
